import { WorkflowStep } from '../../types/robot.types'

/**
 * Generates Fairino robot LUA script from Workflow steps.
 * Uses official Fairino LUA SDK syntax (global functions, standard parameters).
 *
 * NOTE on toDouble():
 * The Fairino controller's LUA runtime may interpret bare numeric literals
 * (e.g. 90, -45) as integer rather than double. Wrapping every numeric
 * argument through the local toDouble() helper guarantees the controller
 * always receives IEEE-754 double-precision floats, avoiding type-mismatch
 * errors in MoveJ/MoveL pose parameters.
 */
export function generateLua(
  steps: WorkflowStep[],
  projectName: string = 'Unnamed Project'
): string {
  const dateStr = new Date().toISOString().split('T')[0]

  let lua = `-- ============================================
-- Generated by FaiRobot Studio v1.0.0
-- Project Name : ${projectName}
-- Robot Model  : Fairino FR5 (6-DOF)
-- Date         : ${dateStr}
-- Note         : Compatible with Fairino Controller LUA SDK
-- ============================================

-- [Utility] Safe string-to-double converter.
-- The Fairino LUA runtime may parse bare integers as integer type;
-- wrapping all numeric literals through toDouble() guarantees they are
-- always treated as double-precision floats by the controller.
local function toDouble(v)
    return tonumber(tostring(v)) + 0.0
end

`

  if (steps.length === 0) {
    lua += `-- No steps recorded yet. Add waypoints in FaiRobot Studio.\n`
    return lua
  }

  // Helper: wrap a JS number as a double-safe toDouble("x.xxx") call.
  // Using string quoting ensures the Fairino LUA runtime parses via tonumber()
  // rather than treating the literal as an integer.
  const d = (n: number, decimals = 3): string => `toDouble("${n.toFixed(decimals)}")`

  const traceMetadata = (step: WorkflowStep): string | null => {
    if (!step.trace || !step.jointAngles) return null

    return JSON.stringify({
      version: 1,
      groupId: step.trace.groupId,
      sampleIndex: step.trace.sampleIndex,
      sampleCount: step.trace.sampleCount,
      segmentDurationMs: Number(step.trace.segmentDurationMs.toFixed(3)),
      jointAngles: step.jointAngles.map((angle) => Number(angle.toFixed(6)))
    })
  }

  steps.forEach((step, idx) => {
    lua += `-- [Bước ${idx + 1}] ${step.label}\n`

    if (step.comment) {
      lua += `-- Ghi chú: ${step.comment}\n`
    }

    const encodedTrace = traceMetadata(step)

    if (encodedTrace) {
      // Optional Studio metadata. A Fairino controller treats this as a normal
      // LUA comment, while Studio can replay the exact recorded joint path.
      lua += `-- @FAIROBOT_TRACE ${encodedTrace}\n`
    }

    switch (step.type) {
      case 'MoveJ':
        if (step.jointAngles) {
          const [j1, j2, j3, j4, j5, j6] = step.jointAngles
          // Format: MoveJ({j1..j6}, tool, user, vel, acc, blendT, blendR)
          lua += `MoveJ({${d(j1)}, ${d(j2)}, ${d(j3)}, ${d(j4)}, ${d(j5)}, ${d(j6)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))\n`
        } else {
          lua += `-- Lỗi: Thiếu thông số góc khớp cho MoveJ\n`
        }
        break

      case 'MoveL':
        if (step.tcpPose) {
          const { x, y, z, rx, ry, rz } = step.tcpPose
          // Format: MoveL({x, y, z, rx, ry, rz}, tool, user, vel, acc, blendT, blendR)
          lua += `MoveL({${d(x)}, ${d(y)}, ${d(z)}, ${d(rx)}, ${d(ry)}, ${d(rz)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))\n`
        } else {
          lua += `-- Lỗi: Thiếu thông số TCP cho MoveL\n`
        }
        break

      case 'RotateJoint':
        if (step.jointAngles) {
          const [j1, j2, j3, j4, j5, j6] = step.jointAngles
          lua += `MoveJ({${d(j1)}, ${d(j2)}, ${d(j3)}, ${d(j4)}, ${d(j5)}, ${d(j6)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))\n`
        } else {
          lua += `-- Lỗi: Chưa giải được góc khớp cho RotateJoint\n`
        }
        break

      case 'MoveTCP':
        if (step.tcpPose) {
          const { x, y, z, rx, ry, rz } = step.tcpPose
          lua += `MoveL({${d(x)}, ${d(y)}, ${d(z)}, ${d(rx)}, ${d(ry)}, ${d(rz)}}, 0, 0, ${d(step.speed, 1)}, ${d(step.acc, 1)}, toDouble("-1.0"), toDouble("-1.0"))\n`
        } else {
          lua += `-- Lỗi: Chưa giải được tọa độ TCP cho MoveTCP\n`
        }
        break

      case 'SetDO': {
        const doIdx = step.doIndex !== undefined ? step.doIndex : 1
        const doVal = step.doValue !== undefined ? step.doValue : 1
        const doType = step.doType || 'cabinet'
        if (doType === 'tool') {
          // Format: SetToolDO(id, status, smooth, block) — these are integer flags, no toDouble needed
          lua += `SetToolDO(${doIdx}, ${doVal}, 0, 0)\n`
        } else {
          // Format: SetDO(index, status, block) — integer flags
          lua += `SetDO(${doIdx}, ${doVal}, 0)\n`
        }
        break
      }

      case 'WaitMs': {
        const delay = step.delayMs !== undefined ? step.delayMs : 1000
        // Format: WaitMs(ms) — ms is integer, no conversion needed
        lua += `WaitMs(${delay})\n`
        break
      }

      case 'GripperOpen':
        // Map to setting DO1 to 0 (default gripper wiring setup)
        lua += `-- Điều khiển mở kẹp tay gắp\n`
        lua += `SetDO(1, 0, 0)\n`
        lua += `WaitMs(500)\n`
        break

      case 'GripperClose':
        // Map to setting DO1 to 1 (default gripper wiring setup)
        lua += `-- Điều khiển đóng kẹp tay gắp\n`
        lua += `SetDO(1, 1, 0)\n`
        lua += `WaitMs(500)\n`
        break

      case 'Comment':
        // Just comments, no code output
        break
    }

    lua += `\n`
  })

  lua += `-- Kết thúc chương trình\n`
  return lua
}
