import { describe, expect, it } from 'vitest'

import type { WorkflowStep } from '../../types/robot.types'
import { generateLua } from './luaCodegen'
import { parseLua } from './luaParser'

describe('parseLua', () => {
  it('parses lay_coc LUA containing toDouble values', () => {
    const lua = `
-- Project Name : coffee_machine_workflow

local function toDouble(v)
    return tonumber(tostring(v)) + 0.0
end

-- [Step 1] Move A
MoveJ({toDouble("0.000"), toDouble("-96.600"), toDouble("-83.500"), toDouble("0.000"), toDouble("0.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Step 2] Move B
MoveJ({toDouble("-91.300"), toDouble("-88.500"), toDouble("-90.000"), toDouble("0.000"), toDouble("0.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Step 3] Delay 05s
WaitMs(5000)

-- [Step 4] Move B
MoveJ({toDouble("-91.300"), toDouble("-88.500"), toDouble("-90.000"), toDouble("0.000"), toDouble("0.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))

-- [Step 5] Move A
MoveJ({toDouble("-175.000"), toDouble("-88.500"), toDouble("-90.000"), toDouble("0.000"), toDouble("0.000"), toDouble("0.000")}, 0, 0, toDouble("30.0"), toDouble("30.0"), toDouble("-1.0"), toDouble("-1.0"))
`

    const result = parseLua(lua)

    expect(result.projectName).toBe('coffee_machine_workflow')
    expect(result.diagnostics).toEqual([])
    expect(result.steps).toHaveLength(5)

    expect(result.steps.map((step) => step.type)).toEqual([
      'MoveJ',
      'MoveJ',
      'WaitMs',
      'MoveJ',
      'MoveJ'
    ])

    expect(result.steps[0]).toMatchObject({
      label: 'Move A',
      jointAngles: [0, -96.6, -83.5, 0, 0, 0],
      speed: 30,
      acc: 30
    })

    expect(result.steps[2]).toMatchObject({
      type: 'WaitMs',
      label: 'Delay 05s',
      delayMs: 5000
    })

    expect(result.steps[4].jointAngles).toEqual([-175, -88.5, -90, 0, 0, 0])
  })

  it('reports unsupported executable statements', () => {
    const result = parseLua('os.execute("dangerous command")')

    expect(result.steps).toHaveLength(0)
    expect(result.diagnostics).toEqual([
      {
        line: 1,
        severity: 'error',
        message: 'Unsupported or malformed LUA statement.',
        source: 'os.execute("dangerous command")'
      }
    ])
  })

  it('rejects MoveJ with fewer than six joint values', () => {
    const result = parseLua('MoveJ({0, 1, 2}, 0, 0, 30, 30, -1, -1)')

    expect(result.steps).toHaveLength(0)
    expect(result.diagnostics[0]).toMatchObject({
      line: 1,
      severity: 'error',
      message: 'MoveJ requires exactly 6 joint values.'
    })
  })

  it('imports LUA generated by luaCodegen', () => {
    const sourceSteps: WorkflowStep[] = [
      {
        id: 'step-1',
        type: 'MoveJ',
        label: 'Test pose',
        jointAngles: [0, -30, 90, 0, 60, 0],
        speed: 20,
        acc: 25
      },
      {
        id: 'step-2',
        type: 'WaitMs',
        label: 'Wait',
        delayMs: 1000,
        speed: 50,
        acc: 50
      }
    ]

    const lua = generateLua(sourceSteps, 'roundtrip_test')
    const result = parseLua(lua)

    expect(result.projectName).toBe('roundtrip_test')
    expect(result.diagnostics).toEqual([])
    expect(result.steps).toHaveLength(2)

    expect(result.steps[0]).toMatchObject({
      type: 'MoveJ',
      jointAngles: [0, -30, 90, 0, 60, 0],
      speed: 20,
      acc: 25
    })

    expect(result.steps[1]).toMatchObject({
      type: 'WaitMs',
      delayMs: 1000
    })
  })

  it('round-trips recorded Cartesian trace joints and timing', () => {
    const trace: WorkflowStep[] = [
      {
        id: 'trace-approach',
        type: 'MoveJ',
        label: 'Trace approach',
        jointAngles: [0, -20, 30, -40, -90, 0],
        speed: 30,
        acc: 30,
        trace: { groupId: 'trace-a', sampleIndex: 0, sampleCount: 2, segmentDurationMs: 0 }
      },
      {
        id: 'trace-point',
        type: 'MoveL',
        label: 'Trace point 1',
        tcpPose: { x: 100, y: 200, z: 300, rx: 0, ry: 90, rz: 0 },
        jointAngles: [1, -19, 31, -39, -89, 1],
        speed: 30,
        acc: 30,
        trace: { groupId: 'trace-a', sampleIndex: 1, sampleCount: 2, segmentDurationMs: 42 }
      }
    ]

    const result = parseLua(generateLua(trace, 'trace_roundtrip'))

    expect(result.diagnostics).toEqual([])
    expect(result.steps[0].trace).toEqual(trace[0].trace)
    expect(result.steps[1]).toMatchObject({
      type: 'MoveL',
      jointAngles: trace[1].jointAngles,
      trace: trace[1].trace
    })
  })
})
